# -*- coding: utf-8 -*-
# Deployment settings for test.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['C:/Marmalade/7.6/s3e/makefile_builder/mkb.py', 'c:/Users/Sean/Documents/C++/Mormalade/test/test.mkb', '--buildenv=VC12X', '--fake-vc-call', '--deploy-only']
mkb = 'c:/Users/Sean/Documents/C++/Mormalade/test/test.mkb'
mkf = ['c:\\marmalade\\7.6\\s3e\\s3e-default.mkf', 'c:\\marmalade\\7.6\\modules\\iwutil\\iwutil.mkf', 'c:\\marmalade\\7.6\\modules\\third_party\\libjpeg\\libjpeg.mkf', 'c:\\marmalade\\7.6\\modules\\third_party\\libpng\\libpng.mkf', 'c:\\marmalade\\7.6\\modules\\third_party\\zlib\\zlib.mkf', 'c:\\marmalade\\7.6\\modules\\iw2dscenegraphcore\\iw2dscenegraphcore.mkf', 'c:\\marmalade\\7.6\\modules\\iw2dscenegraph\\iw2dscenegraph.mkf', 'c:\\marmalade\\7.6\\modules\\iw2d\\iw2d.mkf', 'c:\\marmalade\\7.6\\modules\\iwgx\\iwgx.mkf', 'c:\\marmalade\\7.6\\modules\\iwgl\\iwgl.mkf', 'c:\\marmalade\\7.6\\modules\\iwgeom\\iwgeom.mkf', 'c:\\marmalade\\7.6\\modules\\iwresmanager\\iwresmanager.mkf', 'c:\\marmalade\\7.6\\extensions\\pvrtextool\\pvrtextool.mkf', 'c:\\marmalade\\7.6\\modules\\iwgxfont\\iwgxfont.mkf', 'c:\\marmalade\\7.6\\modules\\third_party\\tiniconv\\tiniconv.mkf', 'c:\\marmalade\\7.6\\modules\\iwtween\\iwtween.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('c:/Users/Sean/Documents/C++/Mormalade/test\data', '.', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'test'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'test'
    long_caption = 'test'
    version = [0, 0, 1]
    config = ['c:/Users/Sean/Documents/C++/Mormalade/test/data/app.icf']
    data_dir = 'c:/Users/Sean/Documents/C++/Mormalade/test/data'
    mkb_dir = 'c:/Users/Sean/Documents/C++/Mormalade/test'
    iphone_link_lib = []
    osx_ext_dll = ['c:/marmalade/7.6/extensions/pvrtextool/lib/osx/libPVRTexTool.dylib']
    wp81_extra_pri = []
    ws8_ext_capabilities = []
    android_external_res = []
    win32_ext_dll = ['c:/marmalade/7.6/extensions/pvrtextool/lib/win32/PVRTexTool.dll']
    wp8_ext_capabilities = []
    ws8_extra_res = []
    ws81_ext_managed_dll = []
    iphone_link_libdir = []
    wp81_ext_capabilities = []
    android_extra_application_manifest = []
    ws8_ext_native_dll = []
    android_external_assets = []
    blackberry_extra_descriptor = []
    android_ext_target_sdk_version = []
    android_extra_manifest = []
    wp81_ext_sdk_ref = []
    iphone_link_libdirs = []
    wp81_ext_device_capabilities = []
    linux_ext_lib = []
    android_ext_min_sdk_version = []
    ws8_ext_managed_dll = []
    ws8_ext_sdk_manifest_part = []
    ws8_ext_device_capabilities = []
    ws81_extra_pri = []
    android_external_jars = []
    win8_winrt_extra_res = []
    wp81_ext_sdk_manifest_part = []
    android_supports_gl_texture = []
    wp81_extra_res = []
    wp81_ext_managed_dll = []
    iphone_extra_plist = []
    ws81_ext_sdk_manifest_part = []
    ws81_ext_device_capabilities = []
    ws8_ext_sdk_ref = []
    iphone_extra_string = []
    tizen_so = []
    wp8_ext_native_dll = []
    win8_phone_extra_res = []
    win8_store_extra_res = []
    iphone_link_opts = []
    ws81_ext_sdk_ref = []
    wp8_extra_res = []
    ws81_ext_native_dll = []
    ws8_extra_pri = []
    wp8_ext_managed_dll = []
    android_extra_packages = []
    android_so = []
    wp8_ext_sdk_ref = []
    osx_extra_res = []
    ws81_extra_res = []
    wp81_ext_native_dll = []
    ws81_ext_capabilities = []
    iphone_link_libs = []
    target = {
         'gcc_x86' : {
                   'debug'   : r'c:/Users/Sean/Documents/C++/Mormalade/test/build_test_vc12x/Debug_test_VC12X_gcc_x86/test.so',
                   'release' : r'c:/Users/Sean/Documents/C++/Mormalade/test/build_test_vc12x/Release_test_VC12X_gcc_x86/test.so',
                 },
         'gcc_x86_tizen' : {
                   'debug'   : r'c:/Users/Sean/Documents/C++/Mormalade/test/build_test_vc12x/Debug_test_VC12X_gcc_x86_tizen/test.s86',
                   'release' : r'c:/Users/Sean/Documents/C++/Mormalade/test/build_test_vc12x/Release_test_VC12X_gcc_x86_tizen/test.s86',
                 },
         'firefoxos' : {
                   'debug'   : r'c:/Users/Sean/Documents/C++/Mormalade/test/build_test_vc12x/Debug_test_VC12X_firefoxos/test.js',
                   'release' : r'c:/Users/Sean/Documents/C++/Mormalade/test/build_test_vc12x/Release_test_VC12X_firefoxos/test.js',
                 },
         'mips_gcc' : {
                   'debug'   : r'c:/Users/Sean/Documents/C++/Mormalade/test/build_test_vc12x/Debug_test_VC12X_gcc_mips/test.so',
                   'release' : r'c:/Users/Sean/Documents/C++/Mormalade/test/build_test_vc12x/Release_test_VC12X_gcc_mips/test.so',
                 },
         'arm_gcc' : {
                   'debug'   : r'c:/Users/Sean/Documents/C++/Mormalade/test/build_test_vc12x/Debug_test_VC12X_gcc_arm/test.s3e',
                   'release' : r'c:/Users/Sean/Documents/C++/Mormalade/test/build_test_vc12x/Release_test_VC12X_gcc_arm/test.s3e',
                 },
         'mips' : {
                   'debug'   : r'c:/Users/Sean/Documents/C++/Mormalade/test/build_test_vc12x/Debug_test_VC12X_gcc_mips/test.so',
                   'release' : r'c:/Users/Sean/Documents/C++/Mormalade/test/build_test_vc12x/Release_test_VC12X_gcc_mips/test.so',
                 },
         'aarch64_gcc' : {
                   'debug'   : r'c:/Users/Sean/Documents/C++/Mormalade/test/build_test_vc12x/Debug_test_VC12X_gcc_aarch64/test.s3e',
                   'release' : r'c:/Users/Sean/Documents/C++/Mormalade/test/build_test_vc12x/Release_test_VC12X_gcc_aarch64/test.s3e',
                 },
         'gcc_x86_android' : {
                   'debug'   : r'c:/Users/Sean/Documents/C++/Mormalade/test/build_test_vc12x/Debug_test_VC12X_gcc_x86_android/test.so',
                   'release' : r'c:/Users/Sean/Documents/C++/Mormalade/test/build_test_vc12x/Release_test_VC12X_gcc_x86_android/test.so',
                 },
         'arm' : {
                   'debug'   : r'c:/Users/Sean/Documents/C++/Mormalade/test/build_test_vc12x/Debug_test_VC12X_arm/test.s3e',
                   'release' : r'c:/Users/Sean/Documents/C++/Mormalade/test/build_test_vc12x/Release_test_VC12X_arm/test.s3e',
                 },
         'x86' : {
                   'debug'   : r'c:/Users/Sean/Documents/C++/Mormalade/test/build_test_vc12x/Debug_test_VC12X_x86/test.s86',
                   'release' : r'c:/Users/Sean/Documents/C++/Mormalade/test/build_test_vc12x/Release_test_VC12X_x86/test.s86',
                 },
        }
    arm_arch = ''
    assets_original = assets
    assets = assets['Default']

default = DefaultConfig()
